apiVersion: exoscale3.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: exo-credentials
      namespace: crossplane-system
      key: credentials
